language: c

# branches safelist
branches:
  only:
  - master
  - develop

services:
  - docker

script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  # deploy develop
  - provider: script
    script: make build
    on:
      branch: develop
  # deploy master (build and push docker image on DockerHub)
  - provider: script
    script: make release
    on:
      branch: master